version: "3"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - data_volume:/data
      - letsencrypt_volume:/etc/letsencrypt
    networks:
      - app_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db:
    image: db_service_image
    volumes:
      - db_data:/data
    networks:
      - app_network
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: backend_service_image
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: frontend_service_image
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  db_data:
  redis_data:
  data_volume:
  letsencrypt_volume:

networks:
  app_network:
    external: true
