name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuración de Docker Login para Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir y empujar imagen de la base de datos
    - name: Build and Push DB Image
      run: |
        docker build -t claudio19/db_service_image ./db
        docker push claudio19/db_service_image

    # Construir y empujar imagen del backend
    - name: Build and Push Backend Image
      run: |
        docker build -t claudio19/backend_service_image ./backend
        docker push claudio19/backend_service_image

    # Construir y empujar imagen del frontend
    - name: Build and Push Frontend Image
      run: |
        docker build -t claudio19/frontend_service_image ./frontend
        docker push claudio19/frontend_service_image
